### ISSUE TITLE
Keeps asking for password

### ISSUE THREAD

**Issue by perfaram** [oleiade/trousseau#168]
I'm on OS X Yosemite (10.10.4), trousseau installed through Homebrew, using GnuPG from https://gpgtools.org
##### With keyring
The key does appear in Keychain Access.
```
$> export TROUSSEAU_KEYRING_SERVICE=GnuPG
$> echo $TROUSSEAU_KEYRING_SERVICE
GnuPG
$> trousseau get abc
Error: no passphrase provided. unable to open data store
```
##### With agent
`/Users/mySelf/.gnupg/S.gpg-agent:18285:1` provided by gpg-agent `write-env-file`
```
$> export GPG_AGENT_INFO=/Users/mySelf/.gnupg/S.gpg-agent:18285:1
$> export TROUSSEAU_MASTER_GPG_ID="mySelf@server.com"
$> echo $GPG_AGENT_INFO
/Users/perfaram/.gnupg/S.gpg-agent:18285:1
$> echo $TROUSSEAU_MASTER_GPG_ID
mySelf@server.com
$> trousseau get abc
Error: no passphrase provided. unable to open data store
```
Any idea on what's going wrong ?
Thanks again for the nice work on Trousseau !

**Comment by temal-** [comment]
Hey, 
there are two easy ways to solve that. If you want to stay on master branch, you should use
```
export gpg_agent_info=foo
```
instead of 
```
export GPG_AGENT_INFO=foo
```
since OS.GetEnv() is case sensitive and the [code](https://github.com/oleiade/trousseau/blob/master/context.go#L63) looks for `gpg_agent_info`.

You could also build your binary from the develop branch since it's already fixed there.

Have fun!

**Comment by perfaram** [comment]
Thanks !
